server:
  port: 8080
  servlet:
    context-path: /nserve

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/nserve"
    username: root
    password: "@@Nserve112233"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        cache-control:
          max-age: 0
          must-revalidate: true
  devtools:
    restart:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379


jwt:
  signerKey: "H1mk8C3kfSBv5QrocE58p+STDAbasBVqAVTJdVoPn+RNFr/wEGIkOxASKQpzcO7a"
  valid-duration: 8000000 # in seconds
  refreshable-duration: 36000  # in second

